### ISSUE TITLE
(0 , _fastEquals.deepEqual) is not a function

### ISSUE THREAD

**Issue by lorenzobalzani** [react-grid-layout/react-grid-layout#1904]
### Describe the bug

I have consistently used version 1.3.4, which was the latest version available on npm. However, yesterday I made the decision to fork the project directly from the source and publish it to npm without making any changes. Surprisingly, I encountered an error upon doing so. It appears that a lot has changed since the version I had been using, which was approximately a year ago, as my code worked perfectly fine with version 1.3.4. Additionally, I want to mention that I installed fast-equals@5.0.0. @STRML, do you have any information regarding this issue? Furthermore, I am curious as to why the package is no longer being published on npm.

```import React , { useState, useContext } from "react";
import { GridContext } from "../Context";
import { WidthProvider, Responsive } from "react-grid-layout";

const ResponsiveReactGridLayout = WidthProvider(Responsive);

export const DnDGrid = (props) => {
  const { myGrid, onUpdatingGrid } = useContext(GridContext);

    return (
        <ResponsiveReactGridLayout
        className="layout"
        cols={{md: 12, sm: 10, xs: 10}} 
        breakpoints={{md: 850, sm: 480, xs:400}} /*Min values to trigger*/
        rowHeight={props.currentBreakpoint === "sm" ? 90 : 80} 
        layouts={myGrid.layouts}
        onLayoutChange={(_, layouts) => {
            if (!props.isLoadingLayout) {
              onUpdatingGrid("layouts", layouts);
            } 
        }}
        onBreakpointChange={newBreakpoint => {
          props.setCurrentBreakpoint(newBreakpoint);
        }}
        autoSize={true}
        compactType={"vertical"}
        containerPadding={{xs:[0, 0], sm: [50, 0], md: [50, 50]}}
        margin={[20, 20]} /*between boxes in the grid*/
        isBounded={props.currentBreakpoint === "xs" ? false : true}
        resizeHandles = {["se"]}>
       

     // The error is present also with no boxes.



      </ResponsiveReactGridLayout>
    )
}
```

### Your Example Website or App

NO APP

### Steps to Reproduce the Bug or Issue

Simply build this repo with `npm run build` and then include it in a simple demo app.

### Expected behavior

The library should work fine as the 1.3.4 version.

### react-grid-layout library version

Repo at 1ec4481

### Operating System Version

macOS

### Browser

Chrome

### Additional context

All my npm packages:
```
├── @auth0/auth0-react@2.1.1
├── @craco/craco@7.1.0
├── @fortawesome/fontawesome-svg-core@6.4.0
├── @fortawesome/free-regular-svg-icons@6.4.0
├── @fortawesome/free-solid-svg-icons@6.4.0
├── @fortawesome/react-fontawesome@0.2.0
├── @radix-ui/react-alert-dialog@1.0.4
├── @radix-ui/react-dialog@1.0.4
├── @radix-ui/react-dropdown-menu@2.0.5
├── @radix-ui/react-label@2.0.2
├── @radix-ui/react-popover@1.0.6
├── @radix-ui/react-separator@1.0.3
├── @radix-ui/react-slot@1.0.2
├── @radix-ui/react-tooltip@1.0.6
├── @reach/combobox@0.18.0
├── @react-google-maps/api@2.18.1
├── @tanstack/react-table@8.9.2
├── @testing-library/jest-dom@5.16.5
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── axios@1.3.6
├── bootstrap-icons@1.10.4
├── bootstrap@5.2.3
├── class-variance-authority@0.6.0
├── clsx@1.2.1
├── cmdk@0.2.0
├── concurrently@8.1.0
├── daisyui@2.51.6
├── deep-equal@2.2.1
├── fast-equals@5.0.0
├── localforage@1.10.0
├── lucide-react@0.236.0
├── react-aws-s3@1.5.0
├── react-bootstrap@2.7.4
├── react-daisyui@3.1.2
├── react-dom@18.2.0
├── react-ga4@2.1.0
├── react-helmet@6.1.0
├── react-joyride@2.5.4
├── react-pdf@7.1.1
├── react-player@2.12.0
├── react-router-dom@6.11.1
├── react-scripts@5.0.1
├── react-sizeme@3.0.2
├── react-textarea-autosize@8.4.1
├── react-youtube@10.1.0
├── react@18.2.0
├── sass@1.62.1
├── source-map-explorer@2.5.3
├── tailwind-merge@1.13.0
├── tailwindcss-animate@1.0.5
├── tailwindcss@3.3.2
├── tripflow-grid@1.0.0 -------> this is my forked version, with NO modifications
├── typed.js@2.0.16
├── typescript@5.1.3
├── use-places-autocomplete@4.0.0
├── web-vitals@2.1.4
└── webpack-bundle-analyzer@4.8.0
```

### Screenshots or Videos

The error is the following:
<img width="1674" alt="Screenshot 2023-07-07 at 4 12 28 PM" src="https://github.com/react-grid-layout/react-grid-layout/assets/45718582/b491b9d0-9859-4bd9-82df-d6742e0d0d9b">

Inspecting with the Google Chrome console:
<img width="614" alt="Screenshot 2023-07-07 at 4 13 06 PM" src="https://github.com/react-grid-layout/react-grid-layout/assets/45718582/570a2663-9830-46c8-9b41-a66a4099a606">

**Comment by xams-creator** [comment]
me too. 
when upgrade to 1.4.0 

in `build/utils.js`  
![1694489739534](https://github.com/react-grid-layout/react-grid-layout/assets/22767166/431aed79-13fa-4579-8f1f-1abede70488c)

**Comment by IlyaAndreevSyberry** [comment]
same problem

**Comment by xams-creator** [comment]
I modified the **package.json** to solve this problem.

```
"overrides": {
    "react-grid-layout": {
        "fast-equals": "4.0.3"
    }
},
```

**Comment by moxpatwa** [comment]
@xams-creator i am facing same issue.. how override i dont know

**Comment by xams-creator** [comment]
> @xams-creator i am facing same issue.. how override i dont know

1.remove package-lock.json and node_modules/react-grid-layout

2.modify package.json

```
{
  "dependencies":{
        "react-grid-layout": "1.4.0"
   },
  "overrides": {
        "react-grid-layout": {
            "fast-equals": "4.0.3"
        }
  }
}
```

3.npm i 

4.check node_modules/fast-equals version
![image](https://github.com/react-grid-layout/react-grid-layout/assets/22767166/7c8a6f05-401f-471c-80bd-903224e94761)

**Comment by ddolcimascolo** [comment]
Same here when trying an upgrade to 1.4.0
```
Uncaught TypeError: (0 , _fastEquals.deepEqual) is not a function
    at getDerivedStateFromProps (ReactGridLayout.js:491:1)
    at applyDerivedStateFromProps (react-dom.development.js:14018:1)
    at mountClassInstance (react-dom.development.js:14490:1)
    at updateClassComponent (react-dom.development.js:19689:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
```

@STRML Anything I can do to help ?

**Comment by moxpatwa** [comment]
@xams-creator after doing above step that you suggest ...facing same issue...I have react 17.0.2

**Comment by ddolcimascolo** [comment]
Guys, for the ones using CRA 5 it turns out to be this issue https://github.com/facebook/create-react-app/issues/11889 that makes Webpack resolve the require'd `.cjs` dependency as a static asset (i.e.: a string). I was using craco already, so fixing that was easy:

Sample craco configuration:
```
{
  webpack: {
    configure(config) {
      const { match: { loader } } = require('@craco/craco').getLoader(config, rule => rule.type === 'asset/resource');

      // Excludes .cjs files also from static assets
      //
      // https://github.com/react-grid-layout/react-grid-layout/issues/1904
      // https://github.com/facebook/create-react-app/issues/11889
      loader.exclude.push(/\.cjs$/);

      return config;
    }
  }
}
```

I'm currently testing v1.4.0 and running into problems, will open new issues once I understand what happens.

Cheers,
David

**Comment by moxpatwa** [comment]
@ddolcimascolo any temp work around is available for above issue as i am using react-grid-layout: 1.3.4 and react 17.0.2 and react-dom 17.0.2

**Comment by EugeneBubnovich** [comment]
The same problem after update to 1.4.0

**Comment by ddolcimascolo** [comment]
> Guys, for the ones using CRA 5 it turns out to be this issue [facebook/create-react-app#11889](https://github.com/facebook/create-react-app/issues/11889) that makes Webpack resolve the require'd `.cjs` dependency as a static asset (i.e.: a string). I was using craco already, so fixing that was easy:
> 
> Sample craco configuration:
> 
> ```
> {
>   webpack: {
>     configure(config) {
>       const { match: { loader } } = require('@craco/craco').getLoader(config, rule => rule.type === 'asset/resource');
> 
>       // Excludes .cjs files also from static assets
>       //
>       // https://github.com/react-grid-layout/react-grid-layout/issues/1904
>       // https://github.com/facebook/create-react-app/issues/11889
>       loader.exclude.push(/\.cjs$/);
> 
>       return config;
>     }
>   }
> }
> ```
> 
> I'm currently testing v1.4.0 and running into problems, will open new issues once I understand what happens.
> 
> Cheers, David

https://github.com/react-grid-layout/react-grid-layout/issues/1929

**Comment by STRML** [comment]
This is pretty odd. It doesn't appear to actually be an issue with RGL, but since we don't use any changes in fast-equals@5, I'm going to roll it back to @4.0.3 and pin it for now.

**Comment by ddolcimascolo** [comment]
> This is pretty odd. It doesn't appear to actually be an issue with RGL, but since we don't use any changes in fast-equals@5, I'm going to roll it back to @4.0.3 and pin it for now.

Totally true, it's a Webpack issue as mentioned in my earlier comment !

**Comment by moxpatwa** [comment]
@STRML and @ddolcimascolo, Thanks for help  and I understand its CRA/Webpack issue...but how i can fix into my existing react project. still facing same issue. I am using latest version node and npm.  or i need to wait for some time to publish your recent fixed into npm

**Comment by moxpatwa** [comment]
@STRML Thanks it is fixed now...Really like your support

**Comment by richard-stafflink** [comment]
I'm using `"react-grid-layout": "^1.5.0"` but getting:

> web [ERROR] Could not resolve "fast-equals"
web | 
web |     ../node_modules/react-grid-layout/build/utils.js:35:26:
web |       35 │ var _fastEquals = require("fast-equals");
web |          ╵                           ~~~~~~~~~~~~~
web | 
web |   You can mark the path "fast-equals" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

I'm also using another package that uses v5 of `fast-equals`
